import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import clxs from 'clsx'
import Footer from '../components/Footer'
import Header from '../components/Header'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="fr">
      <body className={clxs([inter.className, 'min-h-dvh'])}>
      <Header />
        <main className="min-h-dvh">{children}</main>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
